Run for each package, so one file existing doesn't block the rest

diff --git a/script/deploy b/script/deploy
--- a/script/deploy
+++ b/script/deploy
@@ -8,9 +8,12 @@ if [ -z "$PACKAGECLOUD_TOKEN" ]; then
 fi
 
 gem install package_cloud
-package_cloud push lstoll/packages/ubuntu/trusty out/*.deb | tee /tmp/pkgout
-if [ $? != 0 ]; then
-    if ! grep -q "filename: has already been taken" /tmp/pkgout; then
-	exit 1
+for f in $(ls out/*.deb); do
+    package_cloud push lstoll/packages/ubuntu/trusty $f | tee /tmp/pkgout
+    if [ $? != 0 ]; then
+	if ! grep -q "filename: has already been taken" /tmp/pkgout; then
+	    echo "Error occured while pushing package, exiting"
+	    exit 1
+	fi
     fi
-fi
+done
